---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: s11-net
plugin: bridge
args: '[
    {
        "name": "s11-net",
        "type": "bridge",
        "bridge": "s11-net",
        "ipam": {
            "type": "host-local",
            "subnet": "1.1.1.0/24"
        }
    }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: s1u-net
plugin: bridge
args: '[
    {
        "name": "s1u-net",
        "type": "bridge",
        "bridge": "s1u-net",
        "ipam": {
            "type": "host-local",
            "subnet": "2.2.2.0/24"
        }
    }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: sgi-net
plugin: bridge
args: '[
    {
        "name": "sgi-net",
        "type": "bridge",
        "bridge": "sgi-net",
        "ipam": {
            "type": "host-local",
            "subnet": "3.3.3.0/24"
        }
    }
]'

---
apiVersion: "kubernetes.com/v1"
kind: Network
metadata:
  name: cpdp-net
plugin: bridge
args: '[
    {
        "name": "cpdp-net",
        "type": "bridge",
        "bridge": "cpdp-net",
        "ipam": {
            "type": "host-local",
            "subnet": "4.4.4.0/24"
        }
    }
]'
