ERROR_DEPRECATED.
---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: ngic-cp
  annotations:
    networks: '[
        { "name": "s11-net" },
        { "name": "cpdp-net" }
    ]'
spec:
  containers:
  - name: ngic-cp
    image: "ngiccorddemo/ngic-cp:k8s"
    stdin: true
    tty: true
    volumeMounts:
    - name: config-volume
      mountPath: /opt/ngic/config
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: ngic-config

---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: ngic-dp
  annotations:
    networks: '[
        { "name": "s1u-net" },
        { "name": "sgi-net" },
        { "name": "cpdp-net" }
    ]'
spec:
  containers:
  - name: ngic-dp
    image: "ngiccorddemo/ngic-dp:k8s"
    stdin: true
    tty: true
    volumeMounts:
    - name: config-volume
      mountPath: /opt/ngic/config
    securityContext:
      capabilities:
        add:
          - NET_RAW
          - IPC_LOCK
  volumes:
    - name: config-volume
      configMap:
        # Provide the name of the ConfigMap containing the files you want
        # to add to the container
        name: ngic-config

---
apiVersion: v1
kind: Pod # TODO make these deployments later
metadata:
  name: ngic-traffic
  annotations:
    networks: '[
        { "name": "s1u-net" },
        { "name": "sgi-net" },
        { "name": "s11-net" }
    ]'
spec:
  containers:
  - name: ngic-traffic
    image: "ngiccorddemo/ngic-traffic:k8s"
    stdin: true
    tty: true
